import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Cuentera / Storyteller',
      items: [{type: 'autogenerated', dirName: 'cuentera-storyteller'}],
    },
    {
      type: 'category',
      label: 'Maestre de la construcción',
      items: [{type: 'autogenerated', dirName: 'maestre-construccion'}],
    },
    {
      type: 'category',
      label: 'Jardinera de proyectos',
      items: [{type: 'autogenerated', dirName: 'jardinera-proyectos'}],
    },
    {
      type: 'category',
      label: 'Arquitecta de futuros',
      items: [{type: 'autogenerated', dirName: 'arquitecta-futuros'}],
    },
    {
      type: 'category',
      label: 'Investigador',
      items: [{type: 'autogenerated', dirName: 'investigador'}],
    },
    {
      type: 'category',
      label: 'Artista de datos',
      items: [{type: 'autogenerated', dirName: 'artista-datos'}],
    },
    {
      type: 'category',
      label: 'Fundador Tenaz',
      items: [{type: 'autogenerated', dirName: 'fundador-tenaz'}],
    },
    {
      type: 'category',
      label: 'Polo a Tierra',
      items: [{type: 'autogenerated', dirName: 'polo-a-tierra'}],
    },
    {
      type: 'category',
      label: 'Estratega sole voltaje',
      items: [{type: 'autogenerated', dirName: 'estratega-sole-voltaje'}],
    },
    {
      type: 'category',
      label: 'Anarqueologo de los medios',
      items: [{type: 'autogenerated', dirName: 'anarqueologo-medios'}],
    },
    {
      type: 'category',
      label: 'Cacharrero (técnico)',
      items: [{type: 'autogenerated', dirName: 'cacharrero'}],
    },
    {
      type: 'category',
      label: 'Legacy',
      items: [{type: 'autogenerated', dirName: 'legacy'}],
    },
  ],
};

export default sidebars;
